### ISSUE TITLE
Can keypairs.Create().Extract().PrivateKey be a DER encoded key?

### ISSUE THREAD

**Issue by sb10** [gophercloud/gophercloud#210] opened 2016-12-02 10:13 UTC
I'm doing:

    kp, err = keypairs.Create(p.computeClient, keypairs.CreateOpts{Name: resources.ResourceName}).Extract()
    key, err := ssh.ParsePrivateKey([]byte(kp.PrivateKey))

This used to work fine, but now, after an upgrade in our OpenStack installation, I get:

> asn1: structure error: superfluous leading zeros in length

From reading https://github.com/mitchellh/packer/issues/2526 and https://github.com/golang/go/issues/14145, it seems OpenStack produces BER encoded keys, but Go's built-in parser only handles DER.

How are people currently coping with this, and could Gophercloud internally convert BER to DER to make life easier on end-users?

**Comment by rickard-von-essen** [comment] 2017-03-29 07:58
After a lengthy investigation the only viable solution (to not have to write a Go DER decoder) I found was to shell out and try to run OpenSSL to convert the key and get a BER encoded version.

The only inconvenience is on Windows (of course) where _openssl_ is not installed by default otherwise it's kind of transparent.

IMHO OpenStack should revert to only produce DER (which they did before _Liberty_).

For my workaround see https://github.com/mitchellh/packer/pull/3135

**Comment by sb10** [comment] 2017-03-29 08:04
Hmmm. My solution, and my recommendation for Gophercloud, is that when the user of Gophercloud supples keypairs.CreateOpts{...} without PublicKey specified, under the hood Gophercloud creates its own key and injects it:

                    // create a new keypair; we can't just let Openstack create one for
			// us because in latest versions it does not return a DER encoded
			// key, which is what GO built-in library supports.
			privateKey, errk := rsa.GenerateKey(rand.Reader, 1024)
			if errk != nil {
				err = errk
				return
			}
			privateKeyPEM := &pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(privateKey)}
			privateKeyPEMBytes := pem.EncodeToMemory(privateKeyPEM)
			pub, errk := ssh.NewPublicKey(&privateKey.PublicKey)
			if errk != nil {
				err = errk
				return err
			}
			publicKeyStr := ssh.MarshalAuthorizedKey(pub)
                        
                    // inject
                    userKeyparisCreateOpts.PublicKey = string(publicKeyStr)

                    // so that we end up doing the equivalent of:
			kp, err = keypairs.Create(p.computeClient, keypairs.CreateOpts{Name: resources.ResourceName, PublicKey: string(publicKeyStr)}).Extract()
			if err != nil {
				return
			}

**Comment by jtopjian** [comment] 2017-03-29 14:01
> and my recommendation for Gophercloud, is that when the user of Gophercloud supplies keypairs.CreateOpts{...} without PublicKey specified, under the hood Gophercloud creates its own key and injects it

While I think the two parts to this action complement each other very well, I think they are better coupled in a utility/helper function of some sort (implemented in, say, the upcoming CLI) rather than in Gophercloud core.

**Comment by jtopjian** [comment] 2018-06-04 02:46
Looping back around to this issue: I'm able to reproduce the problem in Mitaka, but it looks like this has been resolved in a newer version of OpenStack. I've tested this with Queens and the returned key is readable by Go. I don't know exactly when this was fixed. Looking at the `nova/crypto.py` [history](https://github.com/openstack/nova/commits/master/nova/crypto.py), probably for the Ocata release.

I'm going to close this issue since there's really nothing Gophercloud can do about this. Gophercloud simply sends the request and receives the response. Determining if a pre-made key should be sent or not and parsing the key that is returned should be up to the application which consumes Gophercloud.

**Closed by jtopjian** 2018-06-04 02:46 UTC
