### ISSUE TITLE
Object Storage v1: Container ExtractInfo always fails with unmarshal error

### ISSUE THREAD

**Issue by waynr** [gophercloud/gophercloud#1150] opened 2018-07-25 22:07 UTC
I keep getting the following output whenever I attempt to use https://github.com/gophercloud/gophercloud/blob/f1bae72a73954e0636d2de309b417bcfa4bd7de7/openstack/objectstorage/v1/containers/results.go#L52 on the return value of https://github.com/gophercloud/gophercloud/blob/f1bae72a73954e0636d2de309b417bcfa4bd7de7/openstack/objectstorage/v1/containers/requests.go#L35:

```
json: cannot unmarshal string into Go value of type []containers.Container
```

I'm guessing this is probably due to https://github.com/gophercloud/gophercloud/blob/f1bae72a73954e0636d2de309b417bcfa4bd7de7/openstack/objectstorage/v1/containers/requests.go#L36 which probably means I could get it to work by doing something like https://github.com/gophercloud/gophercloud/blob/f1bae72a73954e0636d2de309b417bcfa4bd7de7/openstack/objectstorage/v1/containers/results.go#L76.

But I'm kind of a lazy bastard and it turns that I can hack around this by not bothering to track `Container` objects since all I really care about for my use case is the container name, but I thought I'd report the bug anyway.

**Comment by jtopjian** [comment] 2018-07-25 22:08
> but I thought I'd report the bug anyway.

It's appreciated! I'll take a look at this when I have some time.

**Comment by jrperritt** [comment] 2018-08-06 18:03
Not a bug; you need to set [`Full`](https://github.com/gophercloud/gophercloud/blob/f1bae72a73954e0636d2de309b417bcfa4bd7de7/openstack/objectstorage/v1/containers/requests.go#L16) to `true`.

**Comment by lblackstone** [comment] 2018-08-22 21:33
I ran across a similar failure, and think I tracked down the root cause. I was getting the error `parsing time "2018-08-22T19:12:11.348Z": extra text: Z`, but the calling path was the same.

I believe the problem line is https://github.com/gophercloud/gophercloud/blob/master/openstack/objectstorage/v1/objects/results.go#L43

As you can see, the timestamp has a `Z` at the end, but the `UnmarshalJSON` method is using the `JSONRFC3339MilliNoZ` format, which causes unmarshalling to fail.

[This review comment](https://github.com/gophercloud/gophercloud/pull/190#pullrequestreview-15160606) from the PR responsible for that line also looks related.

**Comment by jtopjian** [comment] 2018-08-22 21:49
> I confirmed that changing the format to JSONRFC3339Milli fixed the error I was getting.

It's quite possible the time format has always been wrong.

From reviewing the `results.go` file, `JSONRFC3339MilliNoZ` looks to be the odd one out.

**Comment by jtopjian** [comment] 2018-08-24 01:51
I recommend verifying through a known vanilla / unmodified Swift environment. Whatever the result you see there is the one we'll use.

It's quite possible (though I doubt very probable) that `JSONRFC3339MilliNoZ` is correct and the issue you're seeing is due to some local modification done.

**Comment by lblackstone** [comment] 2018-08-24 16:09
Hmm, I just checked the [API docs](https://developer.openstack.org/api-ref/object-store/#get-object-content-and-metadata) which indicate that the last-modified timestamp should be formatted like 
> The date and time is formatted as shown in this example: Fri, 12 Aug 2016 14:24:16 GMT
> The time is always in UTC.

Checking the response via the python openstack CLI, I got that same timestamp format.
```json
{
  "account": "v1", 
  "container": "foo", 
  "object": "bar", 
  "content-length": "297", 
  "last-modified": "Thu, 23 Aug 2018 22:29:30 GMT", 
  "etag": "89b3915b76bbb66bb1ca942e942caaeb", 
  "content-type": "binary/octet-stream"
}
```

Since Swift appears to be returning a completely different timestamp format than the `2018-08-22T19:12:11.348Z` that was causing problems, perhaps this is due to the marshal, unmarshal logic here: https://github.com/gophercloud/gophercloud/blob/2dd96958cf6e3270a81ddfa54004bf4fd01f2b8b/results.go#L56-L60

**Comment by lblackstone** [comment] 2018-08-24 23:05
Ok, after a lot of further digging, I think the actual bug may be that the HTTP response is not being decoded correctly.

Here are the HTTP headers when I hit the API directly using the Postman client:
```
Last-Modified: Thu, 23 Aug 2018 22:29:30 GMT
X-Timestamp: 1535063370.26721
```

Notice that the `Last-Modified` does not include a fractional second, which the `X-Timestamp` (time the object was created) does.

Now, using the gophercloud client, I'm getting the following value:
```
"last_modified": "2018-08-23T22:29:30.267Z"
```

If the HTTP response was being decoded correctly, I wouldn't expect to see the fractional second on that value.

**Comment by jtopjian** [comment] 2018-08-25 03:15
A few notes:

I could have swore we were testing object storage in OpenLab, but it looks like we're not. If we were, this would have been easy to reproduce since the `TestObjects` acceptance test triggers this error.

But at the same time, I wouldn't have added the acceptance test if it didn't work, so I did some investigation.

Turns out the timestamp changed somewhere between Newton and current:

Newton:

```
2018/08/25 03:08:29 [DEBUG] OpenStack Response Body: [{"bytes": 10, "last_modified": "2018-08-25T03:08:29.743220", ...
```

current:

```
2018/08/25 03:11:02 [DEBUG] OpenStack Response Body: ["bytes":10,"last_modified":"2018-08-25T03:10:59.090Z", ...
```

IMO, the best solution is to support both. One way of doing this is to unmarshal the time as a `string` and then trying to parse it as one format, then upon error, parse it as another.

**Comment by lblackstone** [comment] 2018-08-27 15:48
@jtopjian Any thoughts on the `X-Timestamp` vs `Last-Modified` header decoding? I'm not clear if that's a separate issue, or if it would be fixed by updating the unmarshalling code to support both timestamp formats as you suggested.

**Comment by jtopjian** [comment] 2018-08-27 18:47
@lblackstone I'm thinking that's a separate issue. I'm confident that the unmarshalling error you're reporting is related to the notes in my previous comment.

**Comment by lblackstone** [comment] 2018-08-28 23:18
@jtopjian It looks like I was confused on the `X-Timestamp` vs `Last-Modified` issue. It may still be a problem, but if so, it's on the OpenStack side of things.

I realized that I was conflating the responses from two different commands (listing container objects vs get an object). The get command returns a `Last-Modified` header, while the list command includes a `last_modified` field in the JSON response body.

**Comment by jtopjian** [comment] 2018-08-28 23:53
@lblackstone sounds good.

Unfortunately I think there were two separate problems discussed in this issue. Was the first one ever resolved?

**Comment by lblackstone** [comment] 2018-08-29 15:16
@jtopjian Yeah, we can't reproduce the original problem, so I think #1216 fixed it. Can close out this issue now.

**Comment by jrperritt** [comment] 2018-08-29 15:39
> we can't reproduce the original problem, so I think #1216 fixed it

Not quite: the fix for the original issue required no changes to Gophercloud, only to the user code. The time format change between OpenStack versions was a different issue.

**Closed by jrperritt** 2018-08-29 15:39 UTC
