### ISSUE TITLE
https CA problem

### ISSUE THREAD

**Issue by braveliuchina** [gophercloud/gophercloud#311] opened 2017-03-27 11:52 UTC
when i use https as keystone endpoint, it just returned "x509: certificate signed by unknown authority";
are there some examples

**Comment by jtopjian** [comment] 2017-03-27 16:23
You might need to add a intermediate cert to the http client. Here's one such example:

https://github.com/hashicorp/terraform/blob/74189c52111a46a97d88a79fe7becb9892008e81/builtin/providers/openstack/config.go#L66-L85
https://github.com/hashicorp/terraform/blob/74189c52111a46a97d88a79fe7becb9892008e81/builtin/providers/openstack/config.go#L97-L98

This problem isn't specific to Gophercloud per-se. Any example code that describes how to configure a Go http client with CA/intermediate certificates should work here.

Hope that helps!

**Comment by jrperritt** [comment] 2017-06-11 03:00
closing this as not a Gophercloud issue.

**Closed by jrperritt** 2017-06-11 03:00 UTC

**Comment by waynr** [comment] 2018-04-02 21:45
@jtopjian @jrperritt I'm wondering if y'all would be open to a PR that adds support to https://github.com/gophercloud/gophercloud/blob/master/auth_options.go#L30 for an `AdditionalCAPEM` field or some such that would take a base64-encoded PEM that could be obtained from an environment variable `OS_CA_PEM`. I've had to hack this into gophercloud anyway to get past the `x509: certificate signed by unknown authority` message when running acceptance against the openstack environment i have available.

**Comment by jtopjian** [comment] 2018-04-02 22:44
@waynr That kind of support is a bit out of scope for Gophercloud. Gophercloud is easily able to handle situations like this by creating a custom http client. I say "easily" but it's not immediately obvious to those not familiar with how to do so.

This is the example I usually point people towards:

https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/config.go#L102-L157

Though you can ignore the debug and roundtripper stuff. Basically just build a custom http client as seen in the above link and set the Provider Client's `HTTPClient` field with it.

I'm on the fence about whether or not it would be possible to build a helper function for the [`gophercloud/utils`](https://github.com/gophercloud/utils) repo. Customizing the http client is usually very specific to the app in question and a one-size-fits-all solution would be tough to do. However, if you have some ideas on how to create a helper function for something like this, we could definitely take a look and add it to utils.

**Comment by waynr** [comment] 2018-04-02 23:30
My problem isn't that I think that I have to add support to `gophercloud` to support non-system CA certificates for a project that is outside of `gophercloud`

> I've had to hack this into gophercloud anyway to get past the x509: certificate signed by unknown authority message when running acceptance against the openstack environment i have available.

The problem is that I want to write and run acceptance tests to get a different feature that I am working on merged into this repository. In order to do that the simplest thing I could think to do which only requires your permission to also be useful for other potential contributors to and consumers of this library who may have similar experience was the following:

```
diff --git a/acceptance/clients/clients.go b/acceptance/clients/clients.go
index eee80005..822b4c13 100644
--- a/acceptance/clients/clients.go
+++ b/acceptance/clients/clients.go
@@ -466,7 +466,7 @@ func configureDebug(client *gophercloud.ProviderClient) *gophercloud.ProviderCli
 	if os.Getenv("OS_DEBUG") != "" {
 		client.HTTPClient = http.Client{
 			Transport: &LogRoundTripper{
-				Rt: &http.Transport{},
+				Rt: client.HTTPClient.Transport,
 			},
 		}
 	}
diff --git a/auth_options.go b/auth_options.go
index 42114700..c27e35cb 100644
--- a/auth_options.go
+++ b/auth_options.go
@@ -81,6 +81,10 @@ type AuthOptions struct {
 	// TokenID allows users to authenticate (possibly as another user) with an
 	// authentication token ID.
 	TokenID string `json:"-"`
+
+	// AdditionalCAPEMs allows users to specify non-system Root CAs to enable
+	// TLS with self-signed or organization-managed certificates.
+	AdditionalCAPEM string `json:"-"`
 }
 
 // ToTokenV2CreateMap allows AuthOptions to satisfy the AuthOptionsBuilder
diff --git a/openstack/auth_env.go b/openstack/auth_env.go
index b5482ba8..42ca39a5 100644
--- a/openstack/auth_env.go
+++ b/openstack/auth_env.go
@@ -38,6 +38,7 @@ func AuthOptionsFromEnv() (gophercloud.AuthOptions, error) {
 	tenantName := os.Getenv("OS_TENANT_NAME")
 	domainID := os.Getenv("OS_DOMAIN_ID")
 	domainName := os.Getenv("OS_DOMAIN_NAME")
+	pem := os.Getenv("OS_CA_PEM")
 
 	// If OS_PROJECT_ID is set, overwrite tenantID with the value.
 	if v := os.Getenv("OS_PROJECT_ID"); v != "" {
@@ -73,6 +74,7 @@ func AuthOptionsFromEnv() (gophercloud.AuthOptions, error) {
 		TenantName:       tenantName,
 		DomainID:         domainID,
 		DomainName:       domainName,
+		AdditionalCAPEM:  pem,
 	}
 
 	return ao, nil
diff --git a/openstack/client.go b/openstack/client.go
index 5a52e579..b58bd983 100644
--- a/openstack/client.go
+++ b/openstack/client.go
@@ -1,7 +1,11 @@
 package openstack
 
 import (
+	"crypto/tls"
+	"crypto/x509"
+	"encoding/base64"
 	"fmt"
+	"net/http"
 	"net/url"
 	"reflect"
 	"regexp"
@@ -90,6 +94,26 @@ func AuthenticatedClient(options gophercloud.AuthOptions) (*gophercloud.Provider
 		return nil, err
 	}
 
+	if options.AdditionalCAPEM != "" {
+		certBytes, err := base64.StdEncoding.DecodeString(options.AdditionalCAPEM)
+		if err != nil {
+			return nil, err
+		}
+
+		certpool, err := x509.SystemCertPool()
+		if err != nil {
+			return nil, err
+		}
+
+		certpool.AppendCertsFromPEM(certBytes)
+
+		client.HTTPClient.Transport = &http.Transport{
+			TLSClientConfig: &tls.Config{
+				RootCAs: certpool,
+			},
+		}
+	}
+
 	err = Authenticate(client, options)
 	if err != nil {
 		return nil, err
```

I guess the alternative is to write a custom `AuthenticatedClient` implementation for the acceptance tests.

**Comment by jtopjian** [comment] 2018-04-02 23:44
@waynr 

> The problem is that I want to write and run acceptance tests to get a different feature that I am working on merged into this repository. 

Can you provide more details about this different feature? Does it require authentication via SSL certificates? If so, that feature might also be out of scope of Gophercloud.

If you need this support to be able to run Gophercloud in the OpenStack environment which you have access to, then I recommend setting up a separate, small OpenStack cloud to do the testing. Acceptance tests are meant to run in controlled, vanilla OpenStack environments where things like SSL authentication aren't a requirement.

**Comment by waynr** [comment] 2018-04-02 23:57
Okay I get it, not gonna press the issue any more. Thanks for responding to my questions.

For what it's worth I want to support the root ca used by my existing openstack environment in order to reduce cycle time working on https://github.com/gophercloud/gophercloud/issues/234, rather than wait 30 minutes for the automated testing on this repo to finish every time I make changes. The only tests I really need to run are the ones I'm writing (the full set of existing acceptance tests has already passed with my initial implementation in https://github.com/gophercloud/gophercloud/pull/859), and the ones I'm writing don't require anything more than a user with admin privileges on an existing project, which I already have in my existing environment.

I'm not going to spend effort setting up an openstack environment to run acceptance tests for this project when I already have an environment available that works just fine for this purpose. I'll just keep my hack stashed in my local git repo for the next time I have an opportunity to contribute to your project.

**Comment by jtopjian** [comment] 2018-04-03 00:12
OK, understood.

> rather than wait 30 minutes for the automated testing on this repo to finish every time I make changes.

Only a subset of acceptance tests are run at this time. There's intention to get all tests to run in the future, but for now, just a heads up that there's a chance that tests you submit wouldn't be run.

> I'm not going to spend effort setting up an openstack environment to run acceptance tests for this project when I already have an environment available that works just fine for this purpose.

That's understandable. I can certainly appreciate the limited time people have to contribute. 

One option for you would be to make any changes you need to the acceptance test clients defined [here](https://github.com/gophercloud/gophercloud/blob/master/acceptance/clients/clients.go). Then when you want to commit your code, don't commit `clients.go`. In theory that should abstract the changes you need to make in order to authenticate to your environment versus authenticating to a "standard" environment.

**Comment by Lirt** [comment] 2020-07-22 09:16
Here is example on how to disable CA verification if someone still needs it
https://github.com/cisco-sso/velero-plugin-openstack/blob/master/pkg/util/auth.go#L38
