### ISSUE TITLE
[Orchestration]Remove dependency for both stack id and name

### ISSUE THREAD

**Issue by ricolin** [gophercloud/gophercloud#1274] opened 2018-10-09 05:42 UTC
Current Orchestration Stack service requires both Stack name and ID to show a stack. In python SDK, we allow users to only specify either name or ID, since they all identical, it's safe to do so. Users will be easier to use go SDK too (compare with when you have to get both ID and name by yourself).

**Comment by jtopjian** [comment] 2018-10-09 05:49
@ricolin This is a duplicate of #1157 (of which you are part of the discussion :)

**Comment by ricolin** [comment] 2018-10-09 06:05
@jtopjian Right Thanks for the remind:)

**Closed** 2018-10-09 06:06 UTC
