### ISSUE TITLE
Boot From Volume Updates

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#98] opened 2016-09-15 04:25 UTC
I'm pretty sure `DestinationType` is required because I'm getting errors returned whenever it's omitted. 

Additionally, there are only two `DestinationType`s possible, volume and local, so it might be worthwhile to have them as defined types. However, I'm not sure what to do since there's an existing `SourceType` of `Volume` -- have a combined type of `SourceDestinationType` and then check for the allowable ones in the `ToServersCreateMap`?

Also, `VolumeSize` can be omitted in certain situations.

The different combinations of allowed block device options are described [here](http://docs.openstack.org/developer/nova/block_device_mapping.html).

**Comment by jtopjian** [comment] 2016-09-15 04:26
I've done some sketching of these changes [here](https://github.com/jtopjian/gophercloud/commit/30eaaca8450d4aef545cbdb54b77205f6dc7bf07). I don't want to open a PR on it until #94 is taken care of first.

**Comment by jrperritt** [comment] 2016-09-26 17:39
> I'm pretty sure DestinationType is required because I'm getting errors returned whenever it's omitted

Per the style guide, we really need source code proof of the issue and resolution. I don't doubt that you're getting errors, but we can't know the cause for sure without reading the source (e.g. it may be an invalid combination of parameters, an old version of the nova API, etc).

> Also, VolumeSize can be omitted in certain situations.

Same as above.

> The different combinations of allowed block device options are described here.

I know it's tempting to rely on the documentation, but because it isn't auto-generated from the source, it should be considered unreliable.

**Comment by jtopjian** [comment] 2016-09-27 00:11
> Per the style guide, we really need source code proof of the issue and resolution.

I appreciate this enforcement.

AFAICT, Nova is only making `source_type` required [here](https://github.com/openstack/nova/blob/841fc2ecde608a012660828011cf1f5dea322026/nova/block_device.py#L76).

> (e.g. it may be an invalid combination of parameters, an old version of the nova API, etc).

Yes, in this case the error looks to be coming from libvirt. While the error is being caught by Nova, it is not being caught in a way that should make `destination_type` required. This is probably a bug and I'd imagine that this is hypervisor-specific. Therefore, keeping `destination_type` as a non-required field makes sense.

> Also, VolumeSize can be omitted in certain situations.

Reading through the BlockDevice and general Nova API code, there are a number of places where `volume_size` is not checked. 

As for a confident point in the code, there's [this](https://github.com/openstack/nova/blob/ff593bee3433bb40b07f0fea8fc7360c9ef77e0c/nova/virt/block_device.py#L165) function. The omission of `volume_size` does not trigger an exception - an exception is only triggered if the volume size is negative.

This function is being called during the general [_validate](https://github.com/openstack/nova/blob/841fc2ecde608a012660828011cf1f5dea322026/nova/block_device.py#L121) function which, I believe, encompasses all types of block devices.

Additionally, searching that file for `_proxy_as_attr`, I think, shows that `volume_size`, when used with attaching a block storage volume, is only used when a volume needs to be created (the call is then proxied to the Block Storage service). If an existing volume is simply being attached, `volume_size` is not required.

> an old version of the nova API, etc

Side question/comment: I understand what you mean here, but since Gophercloud is a client implementation, not accounting for older API versions (where "older" is arbitrarily defined as "reasonable") might limit its use with certain OpenStack environments. 

For example, let's say someone adds a feature missing in Gophercloud that they wish to use in their n-2 stable OpenStack environment. This feature exists in master, but is implemented slightly different. Should the user:

1. Fork and add the feature the way it's implemented in n-2 so they can use it
2. Add the feature to gophercloud in a way that it can handle both implementations

Obviously this is an edge case, but it might indeed come up since Gophercloud is still in active development. Just curious about if features will only be accepted (similarly, bugs will only be fixed) as they are implemented in master or if there's some flexibility depending on the situation?

**Comment by jrperritt** [comment] 2016-10-12 17:40
> For example, let's say someone adds a feature missing...

I don't understand the example nor the question (what is n-2?), but I'll take a stab at it anyway: This library is meant to be used with OpenStack-proper, yet written in such a way that custom OpenStack implementations can still use it (via eg. `ProviderClient.HTTPClient`, `servers.CreateOptsBuilder`). Pull requests that add features that come built into an OpenStack-proper service will be considered for this library (including extensions).
If I haven't addressed the question, please rephrase.

**Comment by jtopjian** [comment] 2016-10-12 18:16
Sorry about that -- Let me try to clarify a bit:

"n-2" is a term used for supported OpenStack [releases](https://releases.openstack.org/) (at least it _was_, I apologize if that term is no longer being used). We're in a bit of a fuzzy area here with the Newton / Ocata cutover, but until November 17, Liberty is a supported release (n-2) and Mitaka is as well (n-1), and Newton is/was the development release (n).

Operationally, running an OpenStack cloud based on a release within the n to n-2 window is considered to be up-to-date and hasn't fallen behind times.

Let's say a hypothetical parameter existed in Liberty and then removed in Newton: `servers` supported a POST parameter of `foo` but was later removed. 

How would Gophercloud support this at a non-technical level? Are only the latest API parameters supported or is it acceptable to add support for `foo` even if it has been removed in the latest development release? 

As you say, one can alter the implementation by writing their own `servers.CreateOptsBuilder` to support the older `foo`, but what defines "custom" and "proper" OpenStack?

**Comment by jrperritt** [comment] 2016-10-12 18:30
Ah, OK.

> Let's say a hypothetical parameter existed in Liberty and then removed in Newton

Release names aside, have you seen this happen before with respect to a service in two different OpenStack releases when the services had the same major version? If so, I'd say that's a mistake on OpenStack's part. Because they use semantic versioning, any backwards-incompatible change __must__ bump the major version number. In your example, removing a field from an operation would be such a change, and therefore instead of applying the change to Nova v2, it'd go into Nova v3. I know they're moving toward microversions, but even there I'd expect semver practices.

I suppose a direct answer to your question is: This library assumes correct semver practices on the part of OpenStack and therefore would leave the `foo` parameter in its current major version (eg v2), possibly changing it in the next major version (eg v3).

If the `foo` parameter exists in v2.* is removed in v3.*, no issue; Gophercloud will have a new `v3` directory where the new code can reside.

**Comment by jrperritt** [comment] 2016-10-12 18:39
I'm not sure if that answered your question, but I have an addition: You mentioned a change between OpenStack _releases_, but Gophercloud (today) is unaware of the concept of an OpenStack release; it only knows about OpenStack _service versions_, which are quite different things. As far as I know, a release will contain many services, each service having its own version. Backward-incompatible changes to a service will trigger an increase in the version's major number.

**Comment by jtopjian** [comment] 2016-10-12 19:02
Cool - I think we're on the same page now. You did answer my question, so thank you very much.

I'm not aware of an API feature/parameter being outright removed -- that was more of an exaggerated example. Off the top of my head, the closest call I've run into with harmful API changes has been [this](https://github.com/rackspace/gophercloud/pull/598). I'm still fairly new to interacting directly with the OpenStack APIs and so far changes do seem much more safe and much less volatile than, say, configuration options, hypervisor versions, etc, which can wreck havoc from release to release.

Thanks!

**Comment by jrperritt** [comment] 2016-10-13 23:42
closed by #100

**Closed by jrperritt** 2016-10-13 23:42 UTC
