### ISSUE TITLE
Use string in the error body

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#2703] opened 2023-07-20 15:14 UTC
Printing an error shows the following data:

> gophercloud.ErrDefault404={{{ } https://manila/v2/share-replicas/33c6de6a-1965-4ac4-b650-afb14141bbe6 GET [200] 404 [123 34 105 116 101 109 78 111 116 70 111 117 110 100 34 58 32 123 34 99 111 100 101 34 58 32 52 48 52 44 32 34 109 101 115 115 97 103 101 34 58 32 34 82 101 112 108 105 99 97 32 51 51 99 54 100 101 54 97 45 49 57 54 53 45 52 97 99 52 45 98 54 53 48 45 97 102 98 49 52 49 52 49 98 98 101 54 32 110 111 116 32 102 111 117 110 100 46 34 125 125] map[Content-Length:[101] Content-Type:[application/json] Date:[Thu, 20 Jul 2023 15:06:56 GMT] Strict-Transport-Security:[max-age=15724800; includeSubDomains] Vary:[X-OpenStack-Manila-API-Version] X-Compute-Request-Id:[req-883879a2-81c4-4d17-80bf-23625038365d] X-Openstack-Manila-Api-Version:[2.56]]}}

Expected behavior is:

> gophercloud.ErrDefault404={{{ } https://manila/v2/share-replicas/33c6de6a-1965-4ac4-b650-afb14141bbe6 GET [200] 404 {"itemNotFound": {"code": 404, "message": "Replica 33c6de6a-1965-4ac4-b650-afb14141bbe6 not found."}} map[Content-Length:[101] Content-Type:[application/json] Date:[Thu, 20 Jul 2023 15:06:56 GMT] Strict-Transport-Security:[max-age=15724800; includeSubDomains] Vary:[X-OpenStack-Manila-API-Version] X-Compute-Request-Id:[req-883879a2-81c4-4d17-80bf-23625038365d] X-Openstack-Manila-Api-Version:[2.56]]}}

**Comment by pierreprinetti** [comment] 2023-08-03 12:15
Can you please show me the code with which you printed the error?

**Comment by pierreprinetti** [comment] 2023-08-03 13:45
Have you considered implementing [`fmt.Stringer` ](https://pkg.go.dev/fmt#Stringer) for `ErrUnexpectedResponseCode`?

**Comment by kayrus** [comment] 2023-08-08 13:11
@pierreprinetti I think stringer will work only for `%s`. The `%v` prints the err struct members in a pretty convenient way, except the `[]byte` body, and fixing is to the `string` forma actually is the goal.

**Comment by pierreprinetti** [comment] 2023-08-11 07:39
To be clear, the reason why I wouldn’t change the body to be a string altogether, is that the body of an HTTP response is not inherently unicode, nor even ASCII. An HTTP response declaring a MIME content-type of `application/octet-stream` for example [contains arbitrary binary data](https://www.rfc-editor.org/rfc/rfc2046#page-13) and it doesn’t make sense to store it as a string. When defining how to print it to stdout or stderr, then I’d be OK to assume it’s text, and that’s what the String method does.

**Comment by kayrus** [comment] 2023-08-24 13:54
@pierreprinetti 

> An HTTP response declaring a MIME content-type of application/octet-stream for example contains arbitrary binary data and it doesn’t make sense to store it as a string. 

probably we can check for the MIME content type directly inside the `String()` method and print the stuff accordingly. I'd like to keep the default go forma for `%v` when all struct members are printed along the body.

**Comment by kayrus** [comment] 2023-08-24 16:30
@pierreprinetti BTW, are you sure that an error response may contain the binary data?

**Comment by pierreprinetti** [comment] 2023-08-25 08:17
Can you please paste the snippet of code that outputs the error message in your first post? I'd like to show you what I mean with an example

**Comment by kayrus** [comment] 2023-08-25 08:18
`fmt.Printf("%v", err)`

**Comment by pierreprinetti** [comment] 2023-08-25 08:22
I need the full snippet that got you that error, please. I can't reproduce with a simple 404, as the error is intercepted and output as another type.

**Comment by kayrus** [comment] 2023-08-25 08:42
https://github.com/Lirt/velero-plugin-for-openstack/blob/ff31988c0365987b63fdf5906fbce199bf2a04a0/src/manila/fs_store.go#L668

**Comment by pierreprinetti** [comment] 2023-08-25 09:27
The minimal complete reproducer for the code you pointed me at is, if I'm not mistaken:

```Go
package main

import (
	"fmt"
	"os"

	"github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots"
	"github.com/gophercloud/utils/openstack/clientconfig"
)

func main() {
	opts := clientconfig.ClientOpts{Cloud: os.Getenv("OS_CLOUD")}

	client, err := clientconfig.NewServiceClient("volume", &opts)
	if err != nil {
		panic(err)
	}

	randomID := "8000fc73-d7de-44b3-a5b4-a4193f13232a"

	if err := snapshots.Delete(client, randomID).ExtractErr(); err != nil {
		fmt.Printf("%v", err)
	}
}
```

Which gives a well-displayed decoded body:

```shell
$ go run .
Resource not found: [DELETE https://volume.censored.example.com/v3/0693e2bb538c42b79a49fe6d2e61b0fc/snapshots/8000fc73-d7de-44b3-a5b4-a4193f13232a], error message: {"itemNotFound": {"code": 404, "message": "Snapshot 8000fc73-d7de-44b3-a5b4-a4193f13232a could not be found."}}
```

I can only assume you are referring to the other logging line in your code (where `logWithFields` is a `*logrus.Entry`):
```Go
logWithFields.Errorf("failed to delete %s snapshot: %v", snapshotID, err)
```
which is clearly out of scope.

**Comment by kayrus** [comment] 2023-08-25 09:52
I reproduced the initial behavior with the `%w`. Apologies for confusion.

Here is the snippet:

```go
package main

import (
        "net/http"

        "github.com/gophercloud/gophercloud"
        "github.com/gophercloud/gophercloud/openstack"
        "github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/replicas"
        "github.com/gophercloud/utils/client"
        "github.com/gophercloud/utils/openstack/clientconfig"
        log "github.com/sirupsen/logrus"
)

func main() {
        ao, err := clientconfig.AuthOptions(nil)
        if err != nil {
                panic(err)
        }

        provider, err := openstack.NewClient(ao.IdentityEndpoint)
        if err != nil {
                panic(err)
        }

        provider.HTTPClient = http.Client{
                Transport: &client.RoundTripper{
                        Rt:     &http.Transport{},
                        Logger: &client.DefaultLogger{},
                },
        }

        err = openstack.Authenticate(provider, *ao)
        if err != nil {
                panic(err)
        }

        client, err := openstack.NewSharedFileSystemV2(provider, gophercloud.EndpointOpts{})
        if err != nil {
                panic(err)
        }
        client.Microversion = "2.56"

        randomID := "8000fc73-d7de-44b3-a5b4-a4193f13232a"

        if _, err := replicas.Get(client, randomID).Extract(); err != nil {
                log.Printf("test: %w", err)
        }
}
```

**Comment by pierreprinetti** [comment] 2023-08-25 10:19
The function `fmt.Printf` does not support the error-wrapping directive `%w`.

**Comment by kayrus** [comment] 2023-08-25 10:27
yes, I did. I got:

```
test: %!w(gophercloud.ErrDefault404={{{ } https://manila/v2/share-replicas/8000fc73-d7de-44b3-a5b4-a4193f13232a GET [200] 404 [123 34 105 116 101 109 78 111 116 70 111 117 110 100 34 58 32 123 34 99 111 100 101 34 58 32 52 48 52 44 32 34 109 101 115 115 97 103 101 34 58 32 34 82 101 112 108 105 99 97 32 56 48 48 48 102 99 55 51 45 100 55 100 101 45 52 52 98 51 45 97 53 98 52 45 97 52 49 57 51 102 49 51 50 51 50 97 32 110 111 116 32 102 111 117 110 100 46 34 125 125] map[Content-Length:[101] Content-Type:[application/json] Date:[Fri, 25 Aug 2023 10:00:20 GMT] Strict-Transport-Security:[max-age=15724800; includeSubDomains] Vary:[X-OpenStack-Manila-API-Version] X-Compute-Request-Id:[req-ca180fad-0350-4338-b170-2cdde50a1d69] X-Openstack-Manila-Api-Version:[2.56]]}})
```

basically the `%#v` format also prints the data with the more or less desired format, and the `[]byte` member is still confusing.

**Comment by pierreprinetti** [comment] 2023-08-25 11:31
You get `%!w` in the output because `%w` is not a valid directive for `fmt.Printf`. Please provide a valid reproducer or close this issue and the attached PR.

**Closed** 2023-08-25 11:33 UTC
