### ISSUE TITLE
Problem with closing io.Readers

### ISSUE THREAD

**Issue by GiedriusS** [gophercloud/gophercloud#1856] opened 2020-02-16 21:29 UTC
Hello from the Thanos project :wave: Came over from this https://github.com/thanos-io/thanos/pull/1489 issue. This is my rough analysis of the problem:

It seems that AFAICT whenever `Create()` is used, at the end it is passed down to `doRequest()` which does roughly the following: 

```
resp, err := client.HTTPClient.Do(req)
if err != nil {
    return nil, err
}
```

Golang's HTTP client documentation says:
```
// The request Body, if non-nil, will be closed by the underlying                                                                                                                                                
// Transport, even on errors.
```

Thus, it gets closed. Someone has made a PR which makes a new reader on top of a `os.File` thus avoiding the problem. The caller usually expects that the underlying `io.Reader` won't be closed by the callee. 

Maybe I am wrong but this is my impression. Would it be possible to change this behavior in `gophercloud` so that we could avoid adding a workaround? :eye:

**Comment by jtopjian** [comment] 2020-02-16 22:31
@GiedriusS Thank you for reporting this. If I'm understanding the problem correctly, because we are creating a new ReadSeeker [here](https://github.com/gophercloud/gophercloud/blob/master/openstack/objectstorage/v1/objects/requests.go#L199), the original file handle ends up getting closed early - is that accurate?

And if one way of resolving this issue is to manage/defer the connection being closed at the Transport level, I think #1838 is a related issue? One reason I haven't looked into #1838 yet is because I had a feeling that we'd be getting more reports of similar behavior and wanted to first get as much information as I can before possibly getting into a cat-and-mouse game where one fix breaks someone else's environment.

Whether or not #1838 is related, I do want to assist with resolving this issue. There are two ways I can help:

1. If someone can provide me with a succinct way of reproducing the issue (possibly without the use of Thanos), I can look into a solution.

2. Email me directly (my email is on my Github profile page) and I can get you access to a working, modern Swift environment for you and/or your team to work on this problem.

**Comment by jtopjian** [comment] 2020-02-20 04:54
@GiedriusS I've been able to reproduce this and understand what's happening, but I'm not sure yet on what to do.

Reiterating what you've already discovered, the root of this issue is here:

https://github.com/gophercloud/gophercloud/blob/master/openstack/objectstorage/v1/objects/requests.go#L236

and here:

https://github.com/gophercloud/gophercloud/blob/master/openstack/objectstorage/v1/objects/requests.go#L240

When the contents of the object implement `io.ReadSeeker` already, the opened file is being passed directly as the body of the request, thus being closed at the transport.

One solution is to create a copy of the data no matter if `io.ReadSeeker` is implemented or not:

https://github.com/gophercloud/gophercloud/blob/master/openstack/objectstorage/v1/objects/requests.go#L199-L203

The patch you linked to at https://github.com/thanos-io/thanos/pull/1489 is already doing this. It's not so much that the original `r` isn't already an `io.ReadSeeker`, it's that `r` is being copied to something new and thus `r` can be cleanly closed.

And while the files that Thanos works with are possibly relatively small (I'm only assuming), doing this internally with Gophercloud to read in the contents of any object might cause the copying of data which is several gigabytes in size. This is why the file handle is being passed directly to the request body to begin with: it creates a direct stream of bytes rather than having those bytes copied intermediately. 

My next step is to dig into the minio code to see what it's doing differently and why it's not triggering the same error in Thanos. On first glance, minio is [closing the file](https://github.com/minio/minio-go/blob/8730ce1d61167ac1af7ad21ef13493895738390d/api.go#L585-L588), too, but I haven't looked at this into too much detail. This will have to wait another day or two.

**Comment by jtopjian** [comment] 2020-02-20 23:11
@GiedriusS As discussed at https://github.com/thanos-io/thanos/pull/1489, this is the intended behavior for Gophercloud. I've committed a patch at https://github.com/gophercloud/utils/pull/108 that will help avoid this issue by using a more high-level upload function.

Please let me know if you have any questions!

**Closed by jtopjian** 2020-02-20 23:11 UTC
